# NumPy array and basics

In [12]:
import numpy as np

### List vs NumPy Array


In [3]:
import numpy as np
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time = ", time.time() - start)

start = time.time()
py_npArray = np.arange(1000000) * 2
print("\n Numpy arrays operation time = ", time.time() - start)



 List operation time =  0.09447169303894043

 Numpy arrays operation time =  0.009138107299804688


### Creating Array from scratch

In [ ]:
zeros = np.zeros((4, 5)) # creates matrix 4 rows 5 columns
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
