### Advanced Operation with Business example

In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [4]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("=== Companay Data ===")
print("\n Data Shape ", sales_data.shape)
print("1st 3 restaurant", sales_data[:3]) # or you can enter like sales_data[0:3] also more detailed
print("\n1st 3 restaurant", sales_data[:, 1:]) 


=== Companay Data ===

 Data Shape  (5, 5)
1st 3 restaurant [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]

1st 3 restaurant [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]


### Total revenue of all restaurant

In [11]:
print(np.sum(sales_data, axis=0))
yearly_rev = np.sum(sales_data[:, 1:], axis=0)
print(yearly_rev)
print(np.sum(yearly_rev))

[     15  810000  945000 1085000 1240000]
[ 810000  945000 1085000 1240000]
4080000
