### Numpy array Operations

In [1]:
import numpy as np

In [4]:
arr = np.arange(9)
print(arr)
print("Basic Slicing ", arr[2:6])
print("With steps ", arr[1:9:3])

[0 1 2 3 4 5 6 7 8]
Basic Slicing  [2 3 4 5]
With steps  [1 4 7]


In [11]:
arr_2d = np.array([[1,2,3,4],
           [5,6,7,8],
           [9,10,11,12]])

print("2d array elements ", arr_2d[2,2])
print("Particular Row", arr_2d[2])
print("Column printing", arr_2d[:, 3])


2d array elements  11
Particular Row [ 9 10 11 12]
Column printing [ 4  8 12]


### Sorting

In [4]:
unsorted = np.array([4,6,3,8,0,2])
print("sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[1,2], [3,4], [2,3], [5,5]])
print("Sorted 2d array by column  ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2d array by Row  ", np.sort(arr_2d_unsorted, axis=1))

sorted array [0 2 3 4 6 8]
Sorted 2d array by column   [[1 2]
 [2 3]
 [3 4]
 [5 5]]
Sorted 2d array by Row   [[1 2]
 [3 4]
 [2 3]
 [5 5]]


### Filter


In [23]:
# special case
arr_num = np.array([1,2,3,4,5,6,7,8,9,10])
evem_num = (arr_num % 2 == 0)
print(evem_num)

# arr_num = np.arange(0,11)
evem_num = arr_num[arr_num % 2 == 0]
print(evem_num)


[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


### Filter with Mask

In [19]:
mask = arr_num > 4
print("Numbers greater than 4 are ", arr_num[mask])

Numbers greater than 4 are  [ 5  6  7  8  9 10]


### Fancy indexing  vs np.where()

In [26]:
indices = [0,2,4]
print(arr_num[indices])

where_use = np.where(arr_num > 5)
print("Where Result is ", arr_num[where_use])

[1 3 5]
Where Result is  [ 6  7  8  9 10]


In [30]:
condition_arr = np.where(arr_num > 5, arr_num*4, arr_num)
print(condition_arr)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
concatenate = np.concatenate((arr1, arr2))
print(combined)
print(concatenate)

[5 7 9]
[1 2 3 4 5 6]


### Array Compatibilty

In [8]:
com_arr = np.array([1,2,3])
com_arr2 = np.array([4,5,6])
com_arr3 = np.array([7,8,9])

print("Compatiblty shape ", com_arr.shape == com_arr2.shape)

Compatiblty shape  True


In [13]:
original = ([[1,2], [3,4]])
new = ([5,6])

with_new_row = np.vstack((original, new)) #adds a row wise
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col)) #adds columns 
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


### Deleting

In [17]:
darr = np.array([1,2,3,4,5,6])
deleted = np.delete(darr, 3)
print(deleted)

[1 2 3 5 6]
