# NumPy array and basics

In [12]:
import numpy as np

In [13]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3,4,5], [6,7,8,9,0]])
print(arr_2d)


[1 2 3 4 5]
[[1 2 3 4 5]
 [6 7 8 9 0]]


### List vs NumPy Array