# NumPy array and basics

In [12]:
import numpy as np

### List vs NumPy Array


In [3]:
import numpy as np
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time = ", time.time() - start)

start = time.time()
py_npArray = np.arange(1000000) * 2
print("\n Numpy arrays operation time = ", time.time() - start)



 List operation time =  0.09447169303894043

 Numpy arrays operation time =  0.009138107299804688


### Creating Array from scratch

In [5]:
import numpy as np
zeros = np.zeros((4, 5)) # creates matrix 4 rows 5 columns
print(zeros)

ones = np.ones((5, 4)) #5 rows 4 columns
print("Ones array: \n", ones) 

full = np.full((3, 4), 69)
print("Full array: \n", full)

random = np.random.random((3,3))
print("Random array: \n", random)

sequence = np.arange(0, 11, 3)
print("Sequence array: \n", sequence)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array: 
 [[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]]
Random array: 
 [[0.5314855  0.06850878 0.86895713]
 [0.18036581 0.03715587 0.28241899]
 [0.11832317 0.86898563 0.63344514]]
Sequence array: 
 [0 3 6 9]
