# NumPy array and basics

In [12]:
import numpy as np

### List vs NumPy Array


In [3]:
import numpy as np
import time

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time = ", time.time() - start)

start = time.time()
py_npArray = np.arange(1000000) * 2
print("\n Numpy arrays operation time = ", time.time() - start)



 List operation time =  0.09447169303894043

 Numpy arrays operation time =  0.009138107299804688


### Creating Array from scratch

In [6]:
import numpy as np
zeros = np.zeros((4, 5)) # creates matrix 4 rows 5 columns
print(zeros)

ones = np.ones((5, 4)) #5 rows 4 columns
print("Ones array: \n", ones) 

full = np.full((3, 4), 69)
print("Full array: \n", full)

random = np.random.random((3,3))
print("Random array: \n", random)

sequence = np.arange(0, 11, 3)
print("Sequence array: \n", sequence)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Full array: 
 [[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]]
Random array: 
 [[0.7131495  0.73002198 0.30076613]
 [0.44154563 0.7431012  0.96405531]
 [0.865068   0.03706501 0.20936009]]
Sequence array: 
 [0 3 6 9]


### Vector, Matrix and Tensor learning Part

In [2]:
import numpy as np
vector = np.array([1,2,3,4])
print(vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print(matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
print(tensor)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties


In [6]:
import numpy as np
arr = np.array([[1,2,3,4],
               [5,6,7,8]])

print("Shape ", arr.shape)
print("Dimensions ", arr.ndim)
print("Size ", arr.size)
print("Data Type ", arr.dtype)

Shape  (2, 4)
Dimensions  2
Size  8
Data Type  int64


### Array Reshaping

In [28]:
arr = np.arange(12)
print("Original Array ", arr)

reshaped_arr = arr.reshape((3, 4))
print("\n Reshaped Array \n", reshaped_arr)

flattened = reshaped_arr.flatten()
print("\n Flattened Array \n", flattened)

# ravel returns Actual array not the copy but the above methods returns just copy( Returns view, insted of Copy)
ravel = reshaped_arr.ravel()
print("\n Ravel Array \n", ravel)

transpose = reshaped_arr.T
print("\n Transposed Array \n", transpose)

Original Array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped Array 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravel Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Empty , Zero array

In [33]:
emp_arr = np.empty((3, 3))
print("Empty Array  \n", emp_arr)


zero_arr = np.zeros((3, 3))
print("\n Zeros Array \n", zero_arr)

Empty Array  
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 Zeros Array 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Check Whether a Numpy Array contains a Specified Row

In [36]:
arr = np.array([[1,2],
               [3,4]])

row = [4,5]
print(row in arr.tolist()) # Using Funtion tolist()

False
