# Main Interface
## sub
### 3rd sub

---


In [1]:
import numpy as np

In [3]:
print("Again")

Again


#### Remove Rows in Numpy Array that Contains Non-Numeric Values

In [9]:

arr = np.array([[1,2,3],
                [4, 5, 6]])

rmv = arr[np.isfinite(arr).all(axis=1)]

print(rmv)


[[1 2 3]
 [4 5 6]]


In [8]:
#sum of all in array
# def sum_of_elements(arr):
#     # Code Here
#     array = np.array([1, 2, 3, 4, 5])
#     add = np.sum(array)
#     print(add)

def sum_of_elements(arr):
    # Code Here
    return np.sum(arr)

sum_of_elements([1,2,3,4,5])

np.int64(15)

In [7]:
# to find Max no.

def max_element(arr):
    # Code Here
    return np.max(arr)

max_element([1,2,3,4])

np.int64(4)

In [6]:
# Given a Numpy array, write a function to compute the mean (average) of the elements in the array.

def mean_of_elements(arr):
    # Code here
    return np.mean(arr)

mean_of_elements([1,2,3,4,5])

np.float64(3.0)

In [1]:
# Given a Numpy array, write a function to reshape the array into a 2D array with a specified number of rows and columns.

def reshape_array(arr, rows, cols):
    # code here
    return arr.reshape(rows, cols)
    

In [19]:
# Given a Numpy array, write a function to compute the standard deviation of the elements in the array.

def std_deviation_of_elements(arr):
    # Code here
    standard = arr.std()
    print(standard)

std_deviation_of_elements(np.array([1,2,3,4]))


1.118033988749895


In [2]:
# Given a Numpy array, write a function to perform element-wise exponentiation (raise each element to a power)
def elementwise_exponentiation(arr, exp):
    # Code here
    expo = np.power(arr, exp)
    return(expo)

elementwise_exponentiation(np.array([1,2,3,4]), 2)

array([ 1,  4,  9, 16])

In [1]:
#Given two Numpy arrays, write a function to concatenate them along a given axis.
import numpy as np
def concatenate_arrays(arr1, arr2, axis):
    # Code here
    return(np.concatenate((arr1, arr2), axis = axis))

concatenate_arrays(
    np.array([1,2,3]),
    np.array([4,5,6]),
    axis= 0
)

array([1, 2, 3, 4, 5, 6])

In [8]:
# Given a 2D Numpy array, write a function to reverse the rows of the array.

def reverse_rows(arr):
    #code here
    flipped = np.flip(arr, axis=0)
    print(flipped)

reverse_rows(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))

[[7 8 9]
 [4 5 6]
 [1 2 3]]
